/** 量化 API barrel：按域拆到 quant_*，对外仍从本文件导入。 */
export { CapabilityUnavailableError } from '@/shared/api/quant_client'

export {
  getCapabilities,
  getMarketCoverage,
  getMarketSession,
  getLiveTape,
  searchInstruments,
  getMarketBoard,
  getQuotes,
  syncMarket,
  getMarketBootstrap,
  startMarketBootstrap,
  getUniversePresets,
  getUniverseStats,
  previewUniverse,
  getMarketHealth,
  type LiveTapeItem,
  type LiveTape,
  type MarketBootstrapStatus,
} from '@/shared/api/quant_market'

export {
  getStrategies,
  runScreen,
  runBacktest,
  startAnalysis,
  awaitJobResult,
  listCustomStrategies,
  convertStrategy,
  saveConvertedStrategy,
  deleteCustomStrategy,
  getStrategyJob,
  upsertStrategyJob,
  unbindStrategyJob,
  getScreenHistory,
  getScreenToday,
  getDecay,
  getOverlap,
  getStrategyDoc,
  upsertStrategyDoc,
  auditStrategy,
  listAiJudgments,
  createAiJudgment,
} from '@/shared/api/quant_strategy'

export {
  getSkills,
  getSkill,
  installSkill,
  removeSkill,
  startSkillRun,
  getSkillRun,
  replySkillRun,
  getSkillRunEvents,
  generateSkillMd,
  getJobs,
  createJob,
  updateJob,
  deleteJob,
  runJob,
  getJobRuns,
  getScheduleStatus,
  getWecomSettings,
  saveWecomSettings,
  testWecomSettings,
  getMarketSyncSettings,
  saveMarketSyncSettings,
  getDataLocation,
  saveDataLocation,
  createDesktopShortcut,
  fetchLanesCatalog,
  probeLanes,
  speedtestLane,
  patchLaneProvider,
  getProviders,
  saveProvider,
  setDefaultProvider,
  refreshProviderModels,
  testProvider,
  deleteProvider,
  getMcpServers,
  saveMcpServer,
  refreshMcpTools,
  toggleMcpServer,
  deleteMcpServer,
  type SkillRunAsk,
  type SkillRun,
  type DataLocationInfo,
} from '@/shared/api/quant_ops'

export {
  getEquityCurve,
  getRoundTrips,
  getCandidateOutcomes,
  getPlanOutcomes,
  getPositionsAsOf,
  getWinRateSummary,
  getWinRateTrend,
} from '@/shared/api/quant_review'
