/** 量化 API barrel：按域拆到 quant_*，对外仍从本文件导入。 */
export { CapabilityUnavailableError } from '@/shared/api/quant_client'

export {
  getCapabilities,
  getMarketCoverage,
  getMarketSession,
  getLiveTape,
  searchInstruments,
  getMarketBoard,
  getMarketIndustries,
  getQuotes,
  getMinuteBars,
  syncMarket,
  getMarketBootstrap,
  startMarketBootstrap,
  getUniversePresets,
  getUniverseStats,
  getMarketHealth,
  repairMarketTurnover,
  type LiveTapeItem,
  type LiveTape,
  type MinuteBar,
  type MinuteSeries,
  type MarketBootstrapStatus,
  type MarketHealthReport,
  type HealthFinding,
  type HealthRepairPlan,
  type HealthCatalogItem,
} from '@/shared/api/quant_market'

export {
  getStrategies,
  getScreenSkills,
  getScreenSkillCatalog,
  getScreenSkill,
  previewScreenSkill,
  createScreenSkill,
  updateScreenSkill,
  deleteScreenSkill,
  generateScreenSkill,
  startScreenRun,
  getScreenRunStatus,
  runBacktest,
  runHorizonBacktest,
  startAnalysis,
  awaitJobResult,
  listCustomStrategies,
  convertStrategy,
  saveConvertedStrategy,
  deleteCustomStrategy,
  getStrategyJob,
  upsertStrategyJob,
  unbindStrategyJob,
  getScreenHistory,
  getDecay,
  getOverlap,
} from '@/shared/api/quant_strategy'

export {
  getSkills,
  getSkill,
  getSkillJob,
  upsertSkillJob,
  unbindSkillJob,
  installSkill,
  removeSkill,
  startSkillRun,
  getSkillRun,
  replySkillRun,
  getSkillRunEvents,
  getJobs,
  createJob,
  updateJob,
  deleteJob,
  runJob,
  getJobRuns,
  batchDeleteJobRuns,
  getScheduleStatus,
  getWecomSettings,
  saveWecomSettings,
  testWecomSettings,
  getMarketSyncSettings,
  saveMarketSyncSettings,
  getDataLocation,
  saveDataLocation,
  createDesktopShortcut,
  getDesktopPrefs,
  saveDesktopPrefs,
  fetchLanesCatalog,
  probeLanes,
  speedtestLane,
  saveLanePolicy,
  getAkshareCatalog,
  getAkshareSources,
  getAkshareVersion,
  probeAkshareCatalog,
  probeAkshareCatalogBatch,
  patchLaneProvider,
  getProviders,
  saveProvider,
  setDefaultProvider,
  refreshProviderModels,
  updateProviderModels,
  testProvider,
  deleteProvider,
  getMcpServers,
  saveMcpServer,
  refreshMcpTools,
  probeMcpServer,
  toggleMcpServer,
  deleteMcpServer,
  type SkillRunAsk,
  type SkillRun,
  type DataLocationInfo,
  type DesktopPrefs,
  type McpProbeResult,
} from '@/shared/api/quant_ops'

export {
  getEquityCurve,
  getRoundTrips,
  getCandidateOutcomes,
  getPlanOutcomes,
  getWinRateSummary,
  getWinRateTrend,
} from '@/shared/api/quant_review'
