/** 量化 API barrel：按域拆到 quant_*，对外仍从本文件导入。 */
export { CapabilityUnavailableError } from '@/shared/api/quant_client'

export {
  getCapabilities,
  getMarketCoverage,
  getMarketSession,
  getLiveTape,
  searchInstruments,
  getMarketBoard,
  persistMarketBoardSpot,
  getMarketIndustries,
  getQuotes,
  getMinuteBars,
  syncMarket,
  getMarketBootstrap,
  startMarketBootstrap,
  getUniversePresets,
  getUniverseStats,
  getMarketHealth,
  repairMarketTurnover,
  getAkshareCatalog,
  getAkshareSources,
  getAkshareVersion,
  probeAkshareCatalog,
  probeAkshareCatalogBatch,
  type LiveTapeItem,
  type LiveTape,
  type MinuteBar,
  type MinuteSeries,
  type MarketBootstrapStatus,
  type MarketHealthReport,
  type HealthFinding,
  type HealthRepairPlan,
  type HealthCatalogItem,
} from '@/shared/api/quant_market'

export {
  getStrategies,
  getScreenSkills,
  getScreenSkillCatalog,
  getScreenSkill,
  previewScreenSkill,
  createScreenSkill,
  updateScreenSkill,
  deleteScreenSkill,
  generateScreenSkill,
  startScreenRun,
  getScreenRunStatus,
  cancelScreenRun,
  runBacktest,
  runHorizonBacktest,
  startAnalysis,
  awaitJobResult,
  listCustomStrategies,
  convertStrategy,
  saveConvertedStrategy,
  deleteCustomStrategy,
  getStrategyJob,
  upsertStrategyJob,
  unbindStrategyJob,
  getScreenHistory,
  getScreenHistoryBatch,
  getDecay,
  getOverlap,
} from '@/shared/api/quant_strategy'

export {
  getSkills,
  getSkill,
  getSkillJob,
  upsertSkillJob,
  unbindSkillJob,
  getSkillStrategyConfig,
  upsertSkillStrategyConfig,
  installSkill,
  syncSkillTemplates,
  removeSkill,
  startSkillRun,
  getSkillRun,
  replySkillRun,
  getSkillRunEvents,
  getJobs,
  createJob,
  updateJob,
  deleteJob,
  runJob,
  getJobRuns,
  batchDeleteJobRuns,
  getScheduleStatus,
  getJobQuota,
  getWecomSettings,
  saveWecomSettings,
  testWecomSettings,
  getMarketSyncSettings,
  saveMarketSyncSettings,
  getDataLocation,
  saveDataLocation,
  createDesktopShortcut,
  getDesktopPrefs,
  saveDesktopPrefs,
  getAppVersion,
  fetchLanesCatalog,
  probeLanes,
  speedtestLane,
  saveLanePolicy,
  patchLaneProvider,
  getProviders,
  saveProvider,
  setDefaultProvider,
  refreshProviderModels,
  updateProviderModels,
  testProvider,
  deleteProvider,
  getMcpServers,
  saveMcpServer,
  refreshMcpTools,
  probeMcpServer,
  toggleMcpServer,
  deleteMcpServer,
  getMcpQuota,
  saveWudaoMcp,
  saveHithinkMcp,
  patchWudaoSettings,
  type SkillRunAsk,
  type SkillRun,
  type DataLocationInfo,
  type DesktopPrefs,
  type AppVersionInfo,
  type McpProbeResult,
} from '@/shared/api/quant_ops'

export {
  absorbPaperStyle,
  deleteAlertRule,
  downloadSharePack,
  explorePaperMemory,
  getPaperCabin,
  getSharePackStatus,
  listAlertRules,
  rebuildPaperMemory,
  runPaperEod,
  runPaperMonitor,
  saveAlertRule,
  savePaperCabinConfig,
  savePaperStyle,
  scanAlertRules,
  type SharePackOption,
  type SharePackResult,
  type SharePackStatus,
} from '@/shared/api/quant_ops_paper'

export {
  getCandidateOutcomes,
  getPlanOutcomes,
  getWinRateSamples,
  getWinRateSummary,
  getWinRateTrend,
} from '@/shared/api/quant_review'

export { getIntelBrief, type IntelBrief } from '@/shared/api/quant_intel'

export {
  createResearchRun,
  createResearchBacktestRun,
  createResearchHypothesis,
  getResearchCatalog,
  getResearchBacktestRun,
  getResearchBacktestJob,
  getResearchProfile,
  getResearchRun,
  getResearchWorkflow,
  listResearchBacktestRuns,
  listResearchHypotheses,
  researchArtifactUrl,
  replayResearchBacktestRun,
  reviewResearchHypothesis,
  resumeResearchRun,
  submitResearchBacktestJob,
  submitPth252FactorJob,
  getResearchFactorJob,
  transitionResearchHypothesis,
} from '@/shared/api/quant_research'
