"""Public read-only document styling, aligned with the shadcn-vue report surface."""

REPORT_READING_CSS = """
:root{color-scheme:light;--canvas:#fafafa;--paper:#fff;--ink:#18181b;--muted:#65656e;--line:#e4e4e7;--soft:#f4f4f5;--gain:#b42332;--loss:#087b57;--warning:#8b500b}
*{box-sizing:border-box}html{scroll-padding-top:20px}body{margin:0;background:var(--canvas);color:var(--ink);font:15px/1.75 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;-webkit-text-size-adjust:100%}
a{color:inherit;text-underline-offset:3px}a:focus-visible,summary:focus-visible{outline:2px solid var(--muted);outline-offset:4px}.skip{position:fixed;top:-100px;left:16px;padding:10px;background:var(--paper);z-index:10}.skip:focus{top:12px}
.topbar{border-bottom:1px solid var(--line);background:var(--paper)}.topbar>div{max-width:980px;margin:auto;min-height:60px;padding:12px 24px;display:flex;justify-content:space-between;align-items:center;gap:16px}.brand{font-size:21px;font-weight:700;letter-spacing:-.5px}.readonly{font-size:12px;color:var(--muted)}
.sheet{width:calc(100% - 48px);max-width:920px;margin:28px auto;background:var(--paper);border:1px solid var(--line);border-radius:9px;padding:24px 28px 16px;min-width:0}.heading{padding-bottom:8px}.owner{color:var(--muted);font-size:12px}.heading h1{font-size:22px;line-height:1.45;font-weight:650;margin:6px 0 8px;overflow-wrap:anywhere}.metadata{color:var(--muted);font-size:12px;display:flex;gap:8px 16px;flex-wrap:wrap}
.report-section{padding:18px 0;border-bottom:1px solid var(--line);min-width:0}.report-section:last-child{border-bottom:0}.section-heading{display:flex;align-items:baseline;justify-content:space-between;gap:8px 16px;flex-wrap:wrap;margin-bottom:9px}.section-heading h2{font-size:14px;font-weight:650;margin:0;line-height:1.7}.date{font-size:12px;color:var(--muted)}
p{margin:0 0 9px;white-space:normal;overflow-wrap:anywhere}p:last-child{margin-bottom:0}strong{font-weight:600}code{font-size:.9em;word-break:break-word;background:var(--soft);border-radius:3px;padding:1px 3px}.overview{border-bottom:0;padding:12px 0 16px}.overview>.section-heading,.account-brief>.section-heading{display:none}.overview p{font-size:16px;font-weight:550;line-height:1.75}.account-brief{padding:0 0 5px;border:0}
.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:12px 20px;margin:0}.stats dt{font-size:12px;color:var(--muted)}.stats dd{margin:3px 0 0;font-size:15px;font-weight:550;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.account-brief .stats{grid-template-columns:repeat(3,minmax(0,1fr));background:var(--soft);padding:11px 16px;border-radius:6px;gap:16px}.account-brief .stats>div+div{padding-left:16px;border-left:1px solid var(--line)}.account-brief .stats dd{font-size:17px}.gain{color:var(--gain)}.loss{color:var(--loss)}
.plan-table{width:100%;border-collapse:collapse;text-align:left;font-size:15px;line-height:1.75;table-layout:fixed;margin-top:10px}.plan-table th{font-size:12px;font-weight:400;color:var(--muted);padding:6px 10px;background:var(--soft);text-align:left}.plan-table th:first-child{width:190px}.plan-table td{padding:11px 10px;border-bottom:1px solid var(--line);vertical-align:top;overflow-wrap:anywhere}.plan-table tr:last-child td{border:0}.plan-table td:first-child{font-size:13px;font-weight:550}.condition{margin-top:7px;font-size:13px;color:var(--muted)}
.warning{color:var(--warning)}.warning h2{color:var(--warning)}.appendix{margin-top:12px;border-top:1px solid var(--line);font-size:13px}.appendix>summary{cursor:pointer;padding:12px 0;color:var(--muted);font-size:12px}.appendix .report-section{padding:14px 0}.appendix .section-heading h2{font-size:13px}.appendix .stats{grid-template-columns:repeat(auto-fit,minmax(130px,1fr))}.appendix .stats dd{font-size:13px}.appendix .stats dt{font-size:11px}.appendix p{font-size:13px}.page-note{width:calc(100% - 48px);max-width:920px;margin:0 auto 24px;color:var(--muted);font-size:12px}.page-note a{float:right}
@media(max-width:650px){.topbar>div{padding:10px 18px;min-height:52px}.sheet{width:calc(100% - 28px);margin:18px auto;padding:18px 18px 10px}.heading h1{font-size:21px}.metadata{font-size:11px;gap:6px 12px}.overview p{font-size:15px}.account-brief .stats{padding:10px;gap:8px}.account-brief .stats>div+div{padding-left:8px}.account-brief .stats dt{font-size:11px}.account-brief .stats dd{font-size:14px}.report-section{padding:16px 0}.plan-table thead{display:none}.plan-table tbody{display:block}.plan-table tr{display:block;border-bottom:1px solid var(--line);padding:11px 0}.plan-table tr:last-child{border:0}.plan-table td{display:block;border:0;padding:0}.plan-table td:first-child{margin-bottom:6px}.plan-table td:last-child{font-size:15px}.condition{font-size:13px}.page-note{width:calc(100% - 36px);font-size:11px}.page-note a{float:none;display:block;margin-top:8px}.stats{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(prefers-color-scheme:dark){:root{color-scheme:dark;--canvas:#151518;--paper:#1c1c20;--ink:#ededf0;--muted:#a8a8b2;--line:#37373f;--soft:#28282e;--gain:#fb8796;--loss:#6ecfaf;--warning:#f4cd87}}
@media print{:root{--canvas:#fff;--paper:#fff;--ink:#111;--muted:#444;--line:#bbb;--soft:#fff;--gain:#111;--loss:#111;--warning:#111}.topbar,.skip,.page-note a{display:none}.sheet{width:100%;max-width:none;border:0;margin:0;padding:0}.appendix>summary{display:none}.appendix::details-content{content-visibility:visible;height:auto}.report-section,.plan-table tr{break-inside:avoid}.page-note{width:100%;margin-top:18px}}
"""
