/** 量化领域类型门面。保持原有模块路径，具体契约按职责拆分。 */

export type {
  Capabilities,
  MarketCoverage,
  Instrument,
  Bar,
  QuoteSeries,
  BoardRow,
  MarketBoard,
} from './quant-market'

export type {
  Skill,
  JobKind,
  RunStatus,
  Job,
  JobRun,
  ScheduleStatus,
  WecomSettings,
  WecomScreenPreset,
  WecomScreenTemplate,
  MarketSyncSettings,
  DataLane,
  LaneProvider,
  LanePolicyMode,
  LanePolicy,
  LanePolicyPayload,
  LanesSummary,
  LanesCatalog,
  LaneProbeResult,
  LaneProbeResponse,
  LaneProbeRound,
  LaneSpeedTestResult,
  LaneSpeedTestResponse,
} from './quant-ops'

export type {
  JsonValue,
  AkshareCatalogParameter,
  AkshareCatalogCapability,
  AkshareCatalogSource,
  AkshareCatalog,
  AkshareVersionInfo,
  AkshareBatchProbeItem,
  AkshareBatchProbeResult,
  ColumnGloss,
  AkshareCatalogProbeResult,
  LlmModel,
  LlmProvider,
} from './quant-catalog'

export type {
  EquityPoint,
  EquityCurve,
  RoundTrip,
  RoundTripSummary,
  CandidateOutcome,
  CandidateSummary,
  PlanOutcome,
  AnalysisStarted,
} from './quant-review'

export type {
  McpToolRow,
  McpServer,
  StrategyJobSchedule,
  StrategyJobConfig,
  StrategyJob,
  SkillJobConfig,
  SkillJob,
  WinRateSummary,
  WinRateTrendPoint,
  ScreenCandidate,
  ScreenHistory,
  ScreenTodayResult,
  CompareRow,
  CompareResult,
  OptimizeRow,
  OptimizeResult,
} from './quant-jobs'

export type {
  BacktestMetrics,
  BacktestResult,
  BacktestTrade,
  HorizonBacktestResult,
  HorizonEventRef,
  HorizonStats,
  BoardBucket,
  EntryTiming,
  Pick,
  ScreenRecorded,
  ScreenResult,
  ScreenRunStatus,
  ScreenSkillAdjust,
  ScreenSkillCatalog,
  ScreenSkillCatalogDialect,
  ScreenSkillCatalogField,
  ScreenSkillCatalogFunction,
  ScreenSkillCatalogRuntime,
  ScreenSkillCatalogSnippet,
  ScreenSkillDataSpec,
  ScreenSkillDerivedInfo,
  ScreenSkillDetail,
  ScreenSkillDiagnostic,
  ScreenSkillDialect,
  ScreenSkillGenerateRequest,
  ScreenSkillGenerateResponse,
  ScreenSkillLogic,
  ScreenSkillManifest,
  ScreenSkillParamDef,
  ScreenSkillParamType,
  ScreenSkillPreviewExplanation,
  ScreenSkillPreviewResponse,
  ScreenSkillPreviewRun,
  ScreenSkillReference,
  ScreenSkillRuntime,
  ScreenSkillSourceKind,
  ScreenSkillUpsertPayload,
  StrategyInfo,
  StrategyVersion,
  StrategyVersionRollbackResult,
  UniverseFunnel,
  UniversePreset,
  UniverseSpec,
  UniverseStats,
} from '@/shared/types/screenSkill'
