/** 量化领域类型门面。保持原有模块路径，具体契约按职责拆分。 */

export type {
  Capabilities,
  MarketCoverage,
  Instrument,
  Bar,
  QuoteSeries,
  BoardRow,
  MarketBoard,
} from './quant-market'

export type {
  Skill,
  JobKind,
  RunStatus,
  Job,
  JobRun,
  ScheduleStatus,
  JobQuota,
  WecomSettings,
  WecomScreenPreset,
  WecomScreenTemplate,
  MarketSyncSettings,
  DataLane,
  LaneProvider,
  LanePolicyMode,
  LanePolicy,
  LanePolicyPayload,
  LanesSummary,
  LanesCatalog,
  LaneProbeResult,
  LaneProbeResponse,
  LaneProbeRound,
  LaneSpeedTestResult,
  LaneSpeedTestResponse,
} from './quant-ops'

export type {
  JsonValue,
  AkshareCatalogParameter,
  AkshareCatalogCapability,
  AkshareCatalogSource,
  AkshareCatalog,
  AkshareVersionInfo,
  AkshareBatchProbeItem,
  AkshareBatchProbeResult,
  ColumnGloss,
  AkshareCatalogProbeResult,
  LlmModel,
  LlmProvider,
} from './quant-catalog'

export type {
  CandidateOutcome,
  CandidateSummary,
  PlanOutcome,
  AnalysisStarted,
} from './quant-review'

export type {
  McpToolRow,
  McpServer,
  McpQuotaSnapshot,
  StrategyJobSchedule,
  StrategyJobConfig,
  StrategyJob,
  SkillJobConfig,
  SkillJob,
  SkillStrategyConfig,
  SkillWatchPreview,
  SkillWatchSignal,
  SkillWatchPick,
  SkillWatchTheme,
  LeaderMapEntry,
  LeaderRoleSummary,
  MarketGateSnapshot,
  WatchStages,
  WatchTuning,
  WatchTuningResponse,
  WatchTuningSchema,
  WatchTuningPreset,
  WatchTuningSuggestion,
  AuctionStanceRow,
  LeaderRoleTransition,
  LeaderRoleHistoryResponse,
  WinRateSummary,
  WinRateTrendPoint,
  ScreenCandidate,
  ScreenHistory,
  ScreenTodayResult,
  CompareRow,
  CompareResult,
  OptimizeRow,
  OptimizeResult,
} from './quant-jobs'

export type {
  BacktestMetrics,
  BacktestPerformance,
  BacktestPerformancePoint,
  BacktestResult,
  BacktestTrade,
  HorizonBacktestResult,
  HorizonEventRef,
  HorizonPeriodRow,
  HorizonStats,
  BoardBucket,
  EntryTiming,
  Pick,
  ScreenRecorded,
  ScreenResult,
  ScreenRunSlot,
  ScreenRunStatus,
  ScreenSkillAdjust,
  ScreenSkillCatalog,
  ScreenSkillCatalogDialect,
  ScreenSkillCatalogField,
  ScreenSkillCatalogFunction,
  ScreenSkillCatalogRuntime,
  ScreenSkillCatalogSnippet,
  ScreenSkillDataSpec,
  ScreenSkillDerivedInfo,
  ScreenSkillDetail,
  ScreenSkillDiagnostic,
  ScreenSkillDialect,
  ScreenSkillGenerateRequest,
  ScreenSkillGenerateResponse,
  ScreenSkillLogic,
  ScreenSkillManifest,
  ScreenSkillParamDef,
  ScreenSkillParamType,
  ScreenSkillPreviewExplanation,
  ScreenSkillPreviewResponse,
  ScreenSkillPreviewRun,
  ScreenSkillReference,
  ScreenSkillRuntime,
  ScreenSkillSourceKind,
  ScreenSkillUpsertPayload,
  StrategyInfo,
  StrategyVersion,
  StrategyVersionRollbackResult,
  UniverseFunnel,
  UniversePreset,
  UniverseSpec,
  UniverseStats,
} from '@/shared/types/screenSkill'

export type {
  ResearchBudget,
  ResearchBudgetSpec,
  CreateResearchBacktestRunPayload,
  CreateResearchHypothesisPayload,
  CreatePth252FactorJobPayload,
  Pth252FactorSplit,
  ResearchCatalog,
  ResearchArtifactManifestEntry,
  ResearchBacktestRun,
  ResearchBacktestJob,
  ResearchBacktestRunStatus,
  ResearchDimensionResult,
  ResearchDimensionSpec,
  ResearchEvidence,
  ResearchEvidenceLink,
  ResearchProfile,
  ResearchReplayComparison,
  ResearchReplayResult,
  ResearchHypothesis,
  ResearchHypothesisMetric,
  ResearchHypothesisReviewPayload,
  ResearchHypothesisStatus,
  ResearchHypothesisTransitionPayload,
  ResearchQuality,
  ResearchQualitySnapshot,
  ResearchReviewIssue,
  ResearchRun,
  ResearchRunResult,
  ResearchRunStage,
  ResearchSource,
  ResearchSourceAttempt,
  ResearchSourceState,
  ResearchWorkflow,
  ResearchWorkflowEvent,
  ResearchWorkflowStage,
  ResearchWorkflowStageStatus,
} from './quant-research'
