# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/ai/infrastructure/grpc_wire.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'src/ai/infrastructure/grpc_wire.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%src/ai/infrastructure/grpc_wire.proto\x12\x0bloci.llm.v1\"9\n\x08Provider\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\t\"\x16\n\x05Ready\x12\r\n\x05ready\x18\x01 \x01(\x08\"J\n\x0cModelRequest\x12\'\n\x08provider\x18\x01 \x01(\x0b\x32\x15.loci.llm.v1.Provider\x12\x11\n\tjson_body\x18\x02 \x01(\x0c\"V\n\x0fResponseHeaders\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x1d\n\x15upstream_http_version\x18\x03 \x01(\t\"S\n\x05\x46rame\x12/\n\x07headers\x18\x01 \x01(\x0b\x32\x1c.loci.llm.v1.ResponseHeadersH\x00\x12\x0e\n\x04\x62ody\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload2\x7f\n\x0cModelGateway\x12\x32\n\x05\x43heck\x12\x15.loci.llm.v1.Provider\x1a\x12.loci.llm.v1.Ready\x12;\n\x08\x45xchange\x12\x19.loci.llm.v1.ModelRequest\x1a\x12.loci.llm.v1.Frame0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.ai.infrastructure.grpc_wire_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROVIDER']._serialized_start=54
  _globals['_PROVIDER']._serialized_end=111
  _globals['_READY']._serialized_start=113
  _globals['_READY']._serialized_end=135
  _globals['_MODELREQUEST']._serialized_start=137
  _globals['_MODELREQUEST']._serialized_end=211
  _globals['_RESPONSEHEADERS']._serialized_start=213
  _globals['_RESPONSEHEADERS']._serialized_end=299
  _globals['_FRAME']._serialized_start=301
  _globals['_FRAME']._serialized_end=384
  _globals['_MODELGATEWAY']._serialized_start=386
  _globals['_MODELGATEWAY']._serialized_end=513
# @@protoc_insertion_point(module_scope)
