# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.ai.infrastructure import grpc_wire_pb2 as src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/ai/infrastructure/grpc_wire_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelGatewayStub:
    """Credentials and the upstream URL are resolved inside the tenant-bound gateway.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/loci.llm.v1.ModelGateway/Check',
                request_serializer=src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.Provider.SerializeToString,
                response_deserializer=src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.Ready.FromString,
                _registered_method=True)
        self.Exchange = channel.unary_stream(
                '/loci.llm.v1.ModelGateway/Exchange',
                request_serializer=src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.ModelRequest.SerializeToString,
                response_deserializer=src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.Frame.FromString,
                _registered_method=True)


class ModelGatewayServicer:
    """Credentials and the upstream URL are resolved inside the tenant-bound gateway.
    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exchange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.Provider.FromString,
                    response_serializer=src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.Ready.SerializeToString,
            ),
            'Exchange': grpc.unary_stream_rpc_method_handler(
                    servicer.Exchange,
                    request_deserializer=src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.ModelRequest.FromString,
                    response_serializer=src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.Frame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'loci.llm.v1.ModelGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('loci.llm.v1.ModelGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelGateway:
    """Credentials and the upstream URL are resolved inside the tenant-bound gateway.
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/loci.llm.v1.ModelGateway/Check',
            src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.Provider.SerializeToString,
            src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.Ready.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exchange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/loci.llm.v1.ModelGateway/Exchange',
            src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.ModelRequest.SerializeToString,
            src_dot_ai_dot_infrastructure_dot_grpc__wire__pb2.Frame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
