"""运维限界上下文：技能、任务、调度、LLM 配置索引。"""
from src.ops.application.jobs import (
    EXECUTORS,
    JobCancelled,
    JobContext,
    JobError,
    JobTimedOut,
    run_job,
)
from src.ops.infrastructure.scheduler import (
    JobScheduler,
    SchedulerError,
    next_cron_fire_at,
    preview_upcoming_jobs,
    validate_cron,
)
from src.ops.application import skill_runs
from src.ops.application.screen import (
    ScreenPackageError,
    ScreenPackageRecord,
    delete_screen_history,
    delete_screen_package,
    get_screen_package,
    list_screen_history,
    list_screen_packages,
    read_screen_archive,
    restore_screen_package,
    save_screen_package,
)
from src.ops.application.skills import (
    DEFAULT_SKILL_ROOT,
    SkillError,
    SkillPackage,
    discover_skills,
    install_skill,
    install_skill_dir,
    load_skill_from_disk,
    parse_manifest,
    read_skill_file,
    resolve_skill,
    set_skill_enabled,
    uninstall_skill,
)
from src.ops.infrastructure.store import JOB_KINDS, OpsError, OpsStore, new_id
from src.ops.infrastructure.store_helpers import (
    DEFAULT_DB,
    MANAGED_OUTCOME_CRON,
    MANAGED_OUTCOME_TRACK,
    MANAGED_SYNC_EOD,
    MANAGED_SYNC_INTRADAY,
)
from src.ops.infrastructure.model_catalog import (
    enabled_model_ids,
    ensure_default_in_catalog,
    find_model_entry,
    merge_discovered,
    normalize_models,
    present_provider_models,
)

__all__ = [
    "EXECUTORS",
    "DEFAULT_DB",
    "DEFAULT_SKILL_ROOT",
    "JOB_KINDS",
    "MANAGED_OUTCOME_CRON",
    "MANAGED_OUTCOME_TRACK",
    "MANAGED_SYNC_EOD",
    "MANAGED_SYNC_INTRADAY",
    "JobContext",
    "JobCancelled",
    "JobError",
    "JobTimedOut",
    "JobScheduler",
    "OpsError",
    "OpsStore",
    "SchedulerError",
    "SkillError",
    "SkillPackage",
    "discover_skills",
    "enabled_model_ids",
    "ensure_default_in_catalog",
    "find_model_entry",
    "install_skill",
    "install_skill_dir",
    "load_skill_from_disk",
    "merge_discovered",
    "new_id",
    "next_cron_fire_at",
    "normalize_models",
    "parse_manifest",
    "present_provider_models",
    "preview_upcoming_jobs",
    "read_skill_file",
    "resolve_skill",
    "run_job",
    "set_skill_enabled",
    "skill_runs",
    "uninstall_skill",
    "validate_cron",
    # Screen Skill 包存储：strategy 侧编译/注册战法时经包根消费，禁止深引 application.screen
    "ScreenPackageError",
    "ScreenPackageRecord",
    "delete_screen_history",
    "delete_screen_package",
    "get_screen_package",
    "list_screen_history",
    "list_screen_packages",
    "read_screen_archive",
    "restore_screen_package",
    "save_screen_package",
]
